version: '3.7'
services:
  taller38_front:
    container_name: taller38_front
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 2000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true