# POST http://localhost:9000/api/users HTTP/1.1
# Content-Type: application/json

# {
#     "name": "Raul Hurtado",
#     "age": 29,
#     "email": "avellas@uninorte.edu.co"
# }

GET http://localhost:9000/api/users HTTP/1.1

# GET http://localhost:9000/api/users/61b3fd9c6191e51e16849954 HTTP/1.1

# PUT http://localhost:9000/api/users/61b3fd9c6191e51e16849954 HTTP/1.1
# Content-Type: application/json

# {
#     "name": "Santiago Hurtado",
#     "age": 30,
#     "email": "avellas@uninorte.edu.co"
# }

# DELETE http://localhost:9000/api/users/61b3fd9c6191e51e16849954 HTTP/1.1
