version: '3.7'
services:
  taller38_back:
    container_name: taller38_back
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 9000:9000
    environment:
      - CHOKIDAR_USEPOLLING=true